export const AiExecutionResolveUrl = '/ai/execution/resolve';
export const AiExecutionTaskUrl = '/ai/execution/task';
export const AiExecutionTaskDetailUrl = '/ai/execution/task';
export const AiExecutionAgentsUrl = '/ai/execution/agents';
export const AiCaseExecutabilityCheckUrl = '/ai/case-executability/check';
export const AiCaseExecutabilityConfigUrl = '/ai/case-executability/config';
export const AiExecutionObservabilityUrl = '/ai/execution/task';
export const AiExecutionMetricsUrl = '/ai/execution/operations/metrics';
export const AiEnvironmentProfilesUrl = '/ai/environment-profiles';
export const AiEnvironmentProfileUrl = (id: string) => `${AiEnvironmentProfilesUrl}/${id}`;
export const AiEnvironmentProfileVerifyUrl = (id: string) => `${AiEnvironmentProfileUrl(id)}/verify`;
export const AiEnvironmentProfileEnableUrl = (id: string) => `${AiEnvironmentProfileUrl(id)}/enable`;
export const AiEnvironmentProfileDisableUrl = (id: string) => `${AiEnvironmentProfileUrl(id)}/disable`;
export const AiCredentialReferencesUrl = '/ai/credential-references';
export const AiCredentialReferenceUrl = (id: string) => `${AiCredentialReferencesUrl}/${id}`;
export const AiCredentialReferenceVerifyUrl = (id: string) => `${AiCredentialReferenceUrl(id)}/verify`;
export const AiCredentialReferenceEnableUrl = (id: string) => `${AiCredentialReferenceUrl(id)}/enable`;
export const AiCredentialReferenceDisableUrl = (id: string) => `${AiCredentialReferenceUrl(id)}/disable`;
export const AiModelProfilesUrl = '/ai/model-profiles';
export const AiModelProfileUrl = (id: string) => `${AiModelProfilesUrl}/${id}`;
export const AiModelProfileVerifyUrl = (id: string) => `${AiModelProfileUrl(id)}/verify`;
export const AiModelProfileHealthUrl = (id: string) => `${AiModelProfileUrl(id)}/health`;
export const AiModelProfileCapabilitiesUrl = (id: string) => `${AiModelProfileUrl(id)}/capabilities`;
export const AiModelProfileEnableUrl = (id: string) => `${AiModelProfileUrl(id)}/enable`;
export const AiModelProfileDisableUrl = (id: string) => `${AiModelProfileUrl(id)}/disable`;
export const AiExecutionPreflightUrl = '/ai/execution/preflight';
export const AiExecutionPreflightDetailUrl = (id: string) => `${AiExecutionPreflightUrl}/${id}`;
export const AiPromptTemplatesUrl = '/ai/prompt-templates';
export const AiPromptTemplateUrl = (id: string) => `${AiPromptTemplatesUrl}/${id}`;
export const AiPromptTemplatePublishUrl = (id: string) => `${AiPromptTemplateUrl(id)}/publish`;
export const AiPromptTemplatePreviewUrl = (id: string) => `${AiPromptTemplateUrl(id)}/preview`;
export const AiPromptTemplateRollbackUrl = (id: string) => `${AiPromptTemplateUrl(id)}/rollback`;
export const AiModelInvocationsUrl = '/ai/model-invocations';
export const AiModelInvocationUrl = (id: string) => `${AiModelInvocationsUrl}/${id}`;
export const AiModelUsageUrl = `${AiModelInvocationsUrl}/usage`;
export const AiLoginProfilesUrl = '/ai/login-profiles';
export const AiLoginProfileUrl = (id: string) => `${AiLoginProfilesUrl}/${id}`;
export const AiLoginProfileEnableUrl = (id: string) => `${AiLoginProfileUrl(id)}/enable`;
export const AiLoginProfileDisableUrl = (id: string) => `${AiLoginProfileUrl(id)}/disable`;
export const AiPageObjectsUrl = '/ai/page-objects';
export const AiPageObjectUrl = (id: string) => `${AiPageObjectsUrl}/${id}`;
export const AiBusinessFlowsUrl = '/ai/business-flows';
export const AiBusinessFlowUrl = (id: string) => `${AiBusinessFlowsUrl}/${id}`;
export const AiRunnersUrl = '/ai/runner';
export const AiRunnerRegisterUrl = `${AiRunnersUrl}/register`;
export const AiExecutionOperationsUrl = '/ai/execution/operations';
export const AiExecutionOperationsSummaryUrl = `${AiExecutionOperationsUrl}/summary`;
export const AiExecutionOperationsLeasesUrl = `${AiExecutionOperationsUrl}/leases`;
export const AiExecutionAlertsUrl = `${AiExecutionOperationsUrl}/alerts`;
export const acknowledgeAiExecutionAlertUrl = (id: string) => `${AiExecutionAlertsUrl}/${id}/acknowledge`;
export const AiExecutionEvaluationsUrl = '/ai/execution/evaluations';
export const AiExecutionEvaluationSummaryUrl = `${AiExecutionEvaluationsUrl}/summary`;
export const AiExecutionEvaluationManualUrl = (taskId: string) => `${AiExecutionEvaluationsUrl}/task/${taskId}/manual`;
export const AiExecutionEvaluationHistoryUrl = (taskId: string) =>
  `${AiExecutionEvaluationsUrl}/task/${taskId}/history`;
export const AiExecutionTriggersUrl = '/ai/execution/triggers';
export const AiExecutionTriggerUrl = (id: string) => `${AiExecutionTriggersUrl}/${id}`;
export const AiExecutionTriggerFireUrl = (id: string) => `${AiExecutionTriggerUrl(id)}/fire`;
export const AiExecutionTriggerRotateSecretUrl = (id: string) => `${AiExecutionTriggerUrl(id)}/rotate-secret`;
export const AiExecutionTriggerHistoryUrl = (id: string) => `${AiExecutionTriggerUrl(id)}/history`;
export const AiExecutionTaskByIdUrl = (id: string) => `${AiExecutionTaskDetailUrl}/${id}`;
export const AiExecutionTaskSearchUrl = `${AiExecutionTaskUrl}/search`;
export const AiExecutionTaskEventsUrl = (id: string) => `${AiExecutionTaskByIdUrl(id)}/events`;
export const AiExecutionTaskArtifactsUrl = (id: string) => `${AiExecutionTaskByIdUrl(id)}/artifacts`;
export const AiExecutionTaskHumanRequestsUrl = (id: string) => `${AiExecutionTaskByIdUrl(id)}/human-requests`;
export const AiExecutionHumanRequestRespondUrl = (taskId: string, requestId: string) =>
  `${AiExecutionTaskHumanRequestsUrl(taskId)}/${requestId}/respond`;
export const AiExecutionTaskConfirmUrl = (id: string) => `${AiExecutionTaskByIdUrl(id)}/confirm`;
export const AiExecutionTaskCancelUrl = (id: string) => `${AiExecutionTaskByIdUrl(id)}/cancel`;
export const AiExecutionTaskLoginReadyUrl = (id: string) => `${AiExecutionTaskByIdUrl(id)}/login-ready`;
export const AiExecutionTaskPauseUrl = (id: string) => `${AiExecutionTaskByIdUrl(id)}/pause`;
export const AiExecutionTaskRetryUrl = (id: string) => `${AiExecutionTaskByIdUrl(id)}/retry`;
export const AiExecutionTaskObservabilityUrl = (id: string) => `${AiExecutionTaskByIdUrl(id)}/observability`;
export const AiExecutionArtifactDownloadUrl = (taskId: string, artifactId: string) =>
  `${AiExecutionTaskByIdUrl(taskId)}/artifact/${artifactId}`;
export const TestAssetDocumentsUrl = '/test-assets/documents';
export const TestAssetCatalogUrl = '/test-assets/catalog';
export const TestAssetCatalogDetailUrl = (assetType: string, assetId: string) =>
  `${TestAssetCatalogUrl}/${assetType}/${assetId}`;
export const TestAssetVersionsUrl = '/test-assets/versions';
export const TestAssetRelationsUrl = '/test-assets/relations';
