CREATE TABLE wecom_bot_config (
    id VARCHAR(50) NOT NULL,
    organization_id VARCHAR(50) NULL,
    name VARCHAR(100) NOT NULL,
    bot_id VARCHAR(128) NOT NULL,
    secret_ref VARCHAR(255) NULL,
    secret_ciphertext TEXT NULL,
    enabled BIT NOT NULL DEFAULT b'0',
    status VARCHAR(32) NOT NULL DEFAULT 'DISABLED',
    last_connected_at BIGINT NULL,
    last_heartbeat_at BIGINT NULL,
    last_error_code VARCHAR(64) NULL,
    last_error_message VARCHAR(500) NULL,
    create_time BIGINT NOT NULL,
    update_time BIGINT NOT NULL,
    create_user VARCHAR(50) NOT NULL,
    update_user VARCHAR(50) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wecom_bot_id (bot_id),
    KEY idx_wecom_bot_scope (organization_id, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='企业微信智能机器人配置';

CREATE TABLE wecom_bot_chat (
    id VARCHAR(50) NOT NULL,
    bot_config_id VARCHAR(50) NOT NULL,
    chat_id VARCHAR(255) NOT NULL,
    chat_type VARCHAR(16) NOT NULL,
    display_name VARCHAR(255) NULL,
    source_userid VARCHAR(100) NULL,
    active BIT NOT NULL DEFAULT b'0',
    first_seen_at BIGINT NOT NULL,
    last_seen_at BIGINT NOT NULL,
    last_delivery_status VARCHAR(32) NULL,
    last_delivery_at BIGINT NULL,
    metadata TEXT NULL,
    create_time BIGINT NOT NULL,
    update_time BIGINT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wecom_bot_chat (bot_config_id, chat_id),
    KEY idx_wecom_bot_chat_active (bot_config_id, chat_type, active, last_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='企业微信机器人发现会话';

CREATE TABLE wecom_notification_rule (
    id VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    scope_id VARCHAR(50) NULL,
    bot_config_id VARCHAR(50) NOT NULL,
    notification_type VARCHAR(64) NOT NULL,
    trigger_type VARCHAR(32) NOT NULL,
    trigger_config TEXT NULL,
    cron VARCHAR(100) NULL,
    timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
    enabled BIT NOT NULL DEFAULT b'0',
    message_type VARCHAR(32) NOT NULL DEFAULT 'MARKDOWN',
    template TEXT NOT NULL,
    recipient_spec TEXT NOT NULL,
    delivery_mode VARCHAR(32) NOT NULL,
    stop_config TEXT NULL,
    misfire_policy VARCHAR(32) NOT NULL DEFAULT 'DO_NOTHING',
    start_at BIGINT NULL,
    end_at BIGINT NULL,
    next_fire_time BIGINT NULL,
    last_fire_time BIGINT NULL,
    version BIGINT NOT NULL DEFAULT 1,
    create_time BIGINT NOT NULL,
    update_time BIGINT NOT NULL,
    create_user VARCHAR(50) NOT NULL,
    update_user VARCHAR(50) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_wecom_rule_scope (scope_type, scope_id, enabled),
    KEY idx_wecom_rule_type (notification_type, enabled),
    KEY idx_wecom_rule_next_fire (enabled, trigger_type, next_fire_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='企业微信通知规则';

CREATE TABLE wecom_notification_timer (
    id VARCHAR(50) NOT NULL,
    rule_id VARCHAR(50) NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    resource_id VARCHAR(50) NOT NULL,
    resource_version BIGINT NOT NULL,
    deadline_at BIGINT NOT NULL,
    next_fire_at BIGINT NOT NULL,
    fire_count INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'WAITING',
    lease_until BIGINT NULL,
    create_time BIGINT NOT NULL,
    update_time BIGINT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wecom_timer_resource (rule_id, resource_type, resource_id),
    KEY idx_wecom_timer_due (status, next_fire_at),
    KEY idx_wecom_timer_lease (status, lease_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='企业微信临期通知计时器';

CREATE TABLE wecom_notification_outbox (
    id VARCHAR(50) NOT NULL,
    rule_id VARCHAR(50) NULL,
    resource_type VARCHAR(32) NULL,
    resource_id VARCHAR(50) NULL,
    event_type VARCHAR(64) NULL,
    event_id VARCHAR(100) NULL,
    trigger_key VARCHAR(255) NOT NULL,
    target_type VARCHAR(16) NOT NULL,
    target_id VARCHAR(255) NOT NULL,
    message_type VARCHAR(32) NOT NULL DEFAULT 'MARKDOWN',
    payload MEDIUMTEXT NOT NULL,
    payload_preview VARCHAR(500) NULL,
    payload_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempts INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 4,
    next_retry_at BIGINT NULL,
    lease_until BIGINT NULL,
    request_id VARCHAR(100) NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(500) NULL,
    retryable BIT NOT NULL DEFAULT b'0',
    create_time BIGINT NOT NULL,
    update_time BIGINT NOT NULL,
    sent_at BIGINT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wecom_outbox_trigger_target (trigger_key, target_type, target_id),
    KEY idx_wecom_outbox_dispatch (status, next_retry_at, create_time),
    KEY idx_wecom_outbox_lease (status, lease_until),
    KEY idx_wecom_outbox_rule_time (rule_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='企业微信可靠通知发件箱';

CREATE TABLE wecom_bot_callback_event (
    id VARCHAR(100) NOT NULL,
    nonce VARCHAR(100) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    occurred_at BIGINT NOT NULL,
    create_time BIGINT NOT NULL,
    update_time BIGINT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wecom_callback_nonce (nonce),
    KEY idx_wecom_callback_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='企业微信Bridge回调防重放记录';

CREATE INDEX idx_bug_project_expected_resolution
    ON bug(project_id, expected_resolve_time, deleted);
