package io.metersphere.agent.dto;

import lombok.Data;

import java.util.ArrayList;
import java.util.List;

@Data
public class AgentExecutionTaskDTO {
    private String id;
    private String organizationId;
    private String projectId;
    private String testPlanId;
    private String name;
    private String objective;
    private String source;
    private String taskOrigin;
    private String executorChannel;
    private String selectionMode;
    private String prompt;
    private String resolvedFilter;
    private String caseSnapshotHash;
    private String policySnapshot;
    private String contextSnapshot;
    private String contextSnapshotHash;
    private String approvalPolicy;
    private String status;
    private String verdict;
    private String verdictReason;
    private String executionMode;
    private String dispatchMode;
    private String agentType;
    private String agentGatewayId;
    private String requiredCapabilities;
    private String runnerId;
    private String runnerLeaseId;
    private String currentExecutionId;
    private String providerId;
    private String planSchemaVersion;
    private String modelSnapshot;
    private String promptTemplateSnapshot;
    private String executionParameterSnapshot;
    private String traceId;
    private String environmentProfileId;
    private Integer environmentProfileVersion;
    private String credentialReferenceId;
    private String modelProfileId;
    private String promptTemplateVersionId;
    private String preflightId;
    private String executionContract;
    private String executionContractHash;
    private String blockedReason;
    private String blockedDetail;
    private Integer originalScopeCount;
    private Integer expandedScopeCount;
    private java.math.BigDecimal scopeExpansionRate;
    private String environmentId;
    private String targetUrl;
    private String browserType;
    private String loginMode;
    private String idempotencyKey;
    private Boolean confirmRequired;
    private String confirmationReason;
    private Long timeoutAt;
    private Integer maxAttempts;
    private Integer attemptCount;
    private Long finishedAt;
    private Integer totalCount;
    private Integer successCount;
    private Integer failedCount;
    private Integer blockedCount;
    private Integer skippedCount;
    private Integer unexecutedCount;
    private String writebackStatus;
    private String artifactStatus;
    private String executedBy;
    private Long createTime;
    private Long updateTime;
    private String createUser;
    private String updateUser;
    private Integer version;
    private List<AgentExecutionCaseDTO> cases = new ArrayList<>();
}
