package io.metersphere.sdk.constants;

/**
 * @author jianxing
 */
public class PermissionConstants {

    /*------ start: SYSTEM_USER_ROLE ------*/
    public static final String SYSTEM_USER_ROLE_READ = "SYSTEM_USER_ROLE:READ";
    public static final String SYSTEM_USER_ROLE_ADD = "SYSTEM_USER_ROLE:READ+ADD";
    public static final String SYSTEM_USER_ROLE_UPDATE = "SYSTEM_USER_ROLE:READ+UPDATE";
    public static final String SYSTEM_USER_ROLE_DELETE = "SYSTEM_USER_ROLE:READ+DELETE";
    /*------ end: SYSTEM_USER_ROLE ------*/

    /*------ start: SYSTEM_PERMISSION_CONTROL ------*/
    public static final String SYSTEM_PERMISSION_CONTROL_READ = "SYSTEM_PERMISSION_CONTROL:READ";
    public static final String SYSTEM_PERMISSION_CONTROL_ADD = "SYSTEM_PERMISSION_CONTROL:READ+ADD";
    public static final String SYSTEM_PERMISSION_CONTROL_UPDATE = "SYSTEM_PERMISSION_CONTROL:READ+UPDATE";
    public static final String SYSTEM_PERMISSION_CONTROL_DELETE = "SYSTEM_PERMISSION_CONTROL:READ+DELETE";
    /*------ end: SYSTEM_PERMISSION_CONTROL ------*/

    /*------ start: SYSTEM_ORGANIZATION_PROJECT ------*/
    public static final String SYSTEM_ORGANIZATION_PROJECT_READ = "SYSTEM_ORGANIZATION_PROJECT:READ";
    public static final String SYSTEM_ORGANIZATION_PROJECT_READ_ADD = "SYSTEM_ORGANIZATION_PROJECT:READ+ADD";
    public static final String SYSTEM_ORGANIZATION_PROJECT_READ_UPDATE = "SYSTEM_ORGANIZATION_PROJECT:READ+UPDATE";
    public static final String SYSTEM_ORGANIZATION_PROJECT_READ_DELETE = "SYSTEM_ORGANIZATION_PROJECT:READ+DELETE";
    public static final String SYSTEM_ORGANIZATION_PROJECT_READ_RECOVER = "SYSTEM_ORGANIZATION_PROJECT:READ+RECOVER";
    public static final String SYSTEM_ORGANIZATION_PROJECT_MEMBER_ADD = "SYSTEM_ORGANIZATION_PROJECT:READ+ADD_MEMBER";
    public static final String SYSTEM_ORGANIZATION_PROJECT_MEMBER_UPDATE = "SYSTEM_ORGANIZATION_PROJECT:READ+UPDATE_MEMBER";
    public static final String SYSTEM_ORGANIZATION_PROJECT_MEMBER_DELETE = "SYSTEM_ORGANIZATION_PROJECT:READ+DELETE_MEMBER";
    /*------ end: SYSTEM_ORGANIZATION_PROJECT ------*/

    /*------ start: ORGANIZATION_USER_ROLE ------*/
    public static final String ORGANIZATION_USER_ROLE_READ = "ORGANIZATION_USER_ROLE:READ";
    public static final String ORGANIZATION_USER_ROLE_READ_ADD = "ORGANIZATION_USER_ROLE:READ+ADD";
    public static final String ORGANIZATION_USER_ROLE_READ_UPDATE = "ORGANIZATION_USER_ROLE:READ+UPDATE";
    public static final String ORGANIZATION_USER_ROLE_READ_DELETE = "ORGANIZATION_USER_ROLE:READ+DELETE";
    /*------ end: ORGANIZATION_USER_ROLE ------*/

    /*------ start: ORGANIZATION_MEMBER ------*/
    public static final String ORGANIZATION_MEMBER_READ = "ORGANIZATION_MEMBER:READ";
    public static final String ORGANIZATION_MEMBER_ADD = "ORGANIZATION_MEMBER:READ+ADD";
    public static final String ORGANIZATION_MEMBER_INVITE = "ORGANIZATION_MEMBER:READ+INVITE";
    public static final String ORGANIZATION_MEMBER_UPDATE = "ORGANIZATION_MEMBER:READ+UPDATE";
    public static final String ORGANIZATION_MEMBER_DELETE = "ORGANIZATION_MEMBER:READ+DELETE";
    /*------ end: ORGANIZATION_MEMBER ------*/

    /*------ start: ORGANIZATION_PROJECT ------*/
    public static final String ORGANIZATION_PROJECT_READ = "ORGANIZATION_PROJECT:READ";
    public static final String ORGANIZATION_PROJECT_READ_ADD = "ORGANIZATION_PROJECT:READ+ADD";
    public static final String ORGANIZATION_PROJECT_READ_UPDATE = "ORGANIZATION_PROJECT:READ+UPDATE";
    public static final String ORGANIZATION_PROJECT_READ_DELETE = "ORGANIZATION_PROJECT:READ+DELETE";
    public static final String ORGANIZATION_PROJECT_READ_RECOVER = "ORGANIZATION_PROJECT:READ+RECOVER";
    public static final String ORGANIZATION_PROJECT_MEMBER_ADD = "ORGANIZATION_PROJECT:READ+ADD_MEMBER";
    public static final String ORGANIZATION_PROJECT_MEMBER_UPDATE = "ORGANIZATION_PROJECT:READ+UPDATE_MEMBER";
    public static final String ORGANIZATION_PROJECT_MEMBER_DELETE = "ORGANIZATION_PROJECT:READ+DELETE_MEMBER";

    /*------ end: ORGANIZATION_PROJECT ------*/

    /*------ start: SYSTEM_PLUGIN ------*/
    public static final String SYSTEM_PLUGIN_READ = "SYSTEM_PLUGIN:READ";
    public static final String SYSTEM_PLUGIN_ADD = "SYSTEM_PLUGIN:READ+ADD";
    public static final String SYSTEM_PLUGIN_UPDATE = "SYSTEM_PLUGIN:READ+UPDATE";
    public static final String SYSTEM_PLUGIN_DELETE = "SYSTEM_PLUGIN:READ+DELETE";
    /*------ end: SYSTEM_PLUGIN ------*/

    /*------ start: SYSTEM_SERVICE_INTEGRATION ------*/
    public static final String SYSTEM_SERVICE_INTEGRATION_READ = "SYSTEM_SERVICE_INTEGRATION:READ";
    public static final String SYSTEM_SERVICE_INTEGRATION_ADD = "SYSTEM_SERVICE_INTEGRATION:READ+ADD";
    public static final String SYSTEM_SERVICE_INTEGRATION_UPDATE = "SYSTEM_SERVICE_INTEGRATION:READ+UPDATE";
    public static final String SYSTEM_SERVICE_INTEGRATION_DELETE = "SYSTEM_SERVICE_INTEGRATION:READ+DELETE";
    /*------ end: SYSTEM_SERVICE_INTEGRATION ------*/

    /*------ start: SYSTEM_SERVICE_INTEGRATION ------*/
    public static final String SYSTEM_USER_READ = "SYSTEM_USER:READ";
    public static final String SYSTEM_USER_ADD = "SYSTEM_USER:READ+ADD";
    public static final String SYSTEM_USER_IMPORT = "SYSTEM_USER:READ+IMPORT";
    public static final String SYSTEM_USER_UPDATE = "SYSTEM_USER:READ+UPDATE";
    public static final String SYSTEM_USER_INVITE = "SYSTEM_USER:READ+INVITE";
    public static final String SYSTEM_USER_DELETE = "SYSTEM_USER:READ+DELETE";
    /*------ end: SYSTEM_SERVICE_INTEGRATION ------*/

    public static final String SYSTEM_TEST_RESOURCE_POOL_READ = "SYSTEM_TEST_RESOURCE_POOL:READ";
    public static final String SYSTEM_TEST_RESOURCE_POOL_READ_ADD = "SYSTEM_TEST_RESOURCE_POOL:READ+ADD";
    public static final String SYSTEM_TEST_RESOURCE_POOL_READ_UPDATE = "SYSTEM_TEST_RESOURCE_POOL:READ+UPDATE";
    public static final String SYSTEM_TEST_RESOURCE_POOL_READ_DELETE = "SYSTEM_TEST_RESOURCE_POOL:READ+DELETE";


    /*------ start: SYSTEM_PARAMETER_SETTING ------*/
    public static final String SYSTEM_PARAMETER_SETTING_BASE_READ = "SYSTEM_PARAMETER_SETTING_BASE:READ";
    public static final String SYSTEM_PARAMETER_SETTING_BASE_READ_UPDATE = "SYSTEM_PARAMETER_SETTING_BASE:READ+UPDATE";
    public static final String SYSTEM_PARAMETER_SETTING_AUTH_READ = "SYSTEM_PARAMETER_SETTING_AUTH:READ";
    public static final String SYSTEM_PARAMETER_SETTING_AUTH_READ_ADD = "SYSTEM_PARAMETER_SETTING_AUTH:READ+ADD";
    public static final String SYSTEM_PARAMETER_SETTING_AUTH_READ_UPDATE = "SYSTEM_PARAMETER_SETTING_AUTH:READ+UPDATE";
    public static final String SYSTEM_PARAMETER_SETTING_AUTH_READ_DELETE = "SYSTEM_PARAMETER_SETTING_AUTH:READ+DELETE";
    public static final String SYSTEM_PARAMETER_SETTING_DISPLAY_READ = "SYSTEM_PARAMETER_SETTING_DISPLAY:READ";
    public static final String SYSTEM_PARAMETER_SETTING_DISPLAY_READ_UPDATE = "SYSTEM_PARAMETER_SETTING_DISPLAY:READ+UPDATE";
    public static final String SYSTEM_PARAMETER_SETTING_QRCODE_READ = "SYSTEM_PARAMETER_SETTING_QRCODE:READ";
    public static final String SYSTEM_PARAMETER_SETTING_QRCODE_UPDATE = "SYSTEM_PARAMETER_SETTING_QRCODE:READ+UPDATE";
    public static final String SYSTEM_PARAMETER_SETTING_MEMORY_CLEAN_READ = "SYSTEM_PARAMETER_SETTING_MEMORY_CLEAN:READ";
    public static final String SYSTEM_PARAMETER_SETTING_MEMORY_CLEAN_READ_UPDATE = "SYSTEM_PARAMETER_SETTING_MEMORY_CLEAN:READ+UPDATE";
    public static final String SYSTEM_PARAMETER_SETTING_AI_MODEL_READ = "SYSTEM_PARAMETER_SETTING_AI_MODEL:READ";
    public static final String SYSTEM_PARAMETER_SETTING_AI_MODEL_UPDATE = "SYSTEM_PARAMETER_SETTING_AI_MODEL:READ+UPDATE";
    public static final String SYSTEM_AGENT_PACKAGE_READ = "SYSTEM_AGENT_PACKAGE:READ";
    public static final String SYSTEM_AGENT_PACKAGE_ADD = "SYSTEM_AGENT_PACKAGE:READ+ADD";
    public static final String SYSTEM_AGENT_PACKAGE_UPDATE = "SYSTEM_AGENT_PACKAGE:READ+UPDATE";
    public static final String SYSTEM_AGENT_PACKAGE_DELETE = "SYSTEM_AGENT_PACKAGE:READ+DELETE";

    /*------ end: SYSTEM_PARAMETER_SETTING ------*/

    /*------ start: ORGANIZATION_TEMPLATE ------*/
    public static final String ORGANIZATION_TEMPLATE_READ = "ORGANIZATION_TEMPLATE:READ";
    public static final String ORGANIZATION_TEMPLATE_ADD = "ORGANIZATION_TEMPLATE:READ+ADD";
    public static final String ORGANIZATION_TEMPLATE_UPDATE = "ORGANIZATION_TEMPLATE:READ+UPDATE";
    public static final String ORGANIZATION_TEMPLATE_DELETE = "ORGANIZATION_TEMPLATE:READ+DELETE";
    public static final String ORGANIZATION_TEMPLATE_ENABLE = "ORGANIZATION_TEMPLATE:READ+ENABLE";
    /*------ end: ORGANIZATION_TEMPLATE ------*/

    /**
     * 项目成员权限
     */
    /*------ start: PROJECT_USER ------*/
    public static final String PROJECT_USER_READ = "PROJECT_USER:READ";
    public static final String PROJECT_USER_ADD = "PROJECT_USER:READ+ADD";
    public static final String PROJECT_USER_INVITE = "PROJECT_USER:READ+INVITE";
    public static final String PROJECT_USER_UPDATE = "PROJECT_USER:READ+UPDATE";
    public static final String PROJECT_USER_DELETE = "PROJECT_USER:READ+DELETE";
    /*------ end: PROJECT_MEMBER ------*/

    /**
     * 项目用户组
     */
    /*------ start: PROJECT_GROUP ------*/
    public static final String PROJECT_GROUP_READ = "PROJECT_GROUP:READ";
    public static final String PROJECT_GROUP_ADD = "PROJECT_GROUP:READ+ADD";
    public static final String PROJECT_GROUP_UPDATE = "PROJECT_GROUP:READ+UPDATE";
    public static final String PROJECT_GROUP_DELETE = "PROJECT_GROUP:READ+DELETE";
    /*------ end: PROJECT_USER_ROLE ------*/

    public static final String SYSTEM_AUTH_READ = "SYSTEM_AUTH:READ";
    public static final String SYSTEM_AUTH_READ_UPDATE = "SYSTEM_AUTH:READ+UPDATE";

    public static final String SYSTEM_LOG_READ = "SYSTEM_LOG:READ";

    public static final String ORGANIZATION_LOG_READ = "ORGANIZATION_LOG:READ";
    public static final String PROJECT_LOG_READ = "PROJECT_LOG:READ";

    public static final String PROJECT_USER_READ_ADD = "PROJECT_USER:READ+ADD";
    public static final String PROJECT_USER_READ_DELETE = "PROJECT_USER:READ+DELETE";


    /*------ start: PROJECT_MESSAGE ------*/
    public static final String PROJECT_MESSAGE_READ = "PROJECT_MESSAGE:READ";
    public static final String PROJECT_MESSAGE_READ_UPDATE = "PROJECT_MESSAGE:READ+UPDATE";
    public static final String PROJECT_MESSAGE_READ_ADD = "PROJECT_MESSAGE:READ+ADD";
    public static final String PROJECT_MESSAGE_READ_DELETE = "PROJECT_MESSAGE:READ+DELETE";
    /*------ end: PROJECT_MESSAGE ------*/

    /*------ start: PROJECT_APPLICATION ------*/
    public static final String PROJECT_APPLICATION_TEST_PLAN_READ = "PROJECT_APPLICATION_TEST_PLAN:READ";
    public static final String PROJECT_APPLICATION_TEST_PLAN_UPDATE = "PROJECT_APPLICATION_TEST_PLAN:UPDATE";
    public static final String PROJECT_APPLICATION_UI_READ = "PROJECT_APPLICATION_UI:READ";
    public static final String PROJECT_APPLICATION_UI_UPDATE = "PROJECT_APPLICATION_UI:UPDATE";
    public static final String PROJECT_APPLICATION_PERFORMANCE_TEST_READ = "PROJECT_APPLICATION_PERFORMANCE_TEST:READ";
    public static final String PROJECT_APPLICATION_PERFORMANCE_TEST_UPDATE = "PROJECT_APPLICATION_PERFORMANCE_TEST:UPDATE";
    public static final String PROJECT_APPLICATION_API_READ = "PROJECT_APPLICATION_API:READ";
    public static final String PROJECT_APPLICATION_API_UPDATE = "PROJECT_APPLICATION_API:UPDATE";
    public static final String PROJECT_APPLICATION_TASK_READ = "PROJECT_APPLICATION_TASK:READ";
    public static final String PROJECT_APPLICATION_TASK_UPDATE = "PROJECT_APPLICATION_TASK:UPDATE";
    public static final String PROJECT_APPLICATION_CASE_READ = "PROJECT_APPLICATION_CASE:READ";
    public static final String PROJECT_APPLICATION_CASE_UPDATE = "PROJECT_APPLICATION_CASE:UPDATE";
    public static final String PROJECT_APPLICATION_BUG_READ = "PROJECT_APPLICATION_BUG:READ";
    public static final String PROJECT_APPLICATION_BUG_UPDATE = "PROJECT_APPLICATION_BUG:UPDATE";
    public static final String PROJECT_APPLICATION_WORKSTATION_READ = "PROJECT_APPLICATION_WORKSTATION:READ";
    public static final String PROJECT_APPLICATION_WORKSTATION_UPDATE = "PROJECT_APPLICATION_WORKSTATION:UPDATE";
    /*------ end: PROJECT_APPLICATION ------*/
    public static final String PROJECT_BASE_INFO_READ = "PROJECT_BASE_INFO:READ";
    public static final String PROJECT_BASE_INFO_READ_UPDATE = "PROJECT_BASE_INFO:READ+UPDATE";

    /**
     * 项目环境权限
     */
    /*------ start: PROJECT_ENVIRONMENT ------*/
    public static final String PROJECT_ENVIRONMENT_READ = "PROJECT_ENVIRONMENT:READ";
    public static final String PROJECT_ENVIRONMENT_READ_ADD = "PROJECT_ENVIRONMENT:READ+ADD";
    public static final String PROJECT_ENVIRONMENT_READ_UPDATE = "PROJECT_ENVIRONMENT:READ+UPDATE";
    public static final String PROJECT_ENVIRONMENT_READ_DELETE = "PROJECT_ENVIRONMENT:READ+DELETE";
    public static final String PROJECT_ENVIRONMENT_READ_IMPORT = "PROJECT_ENVIRONMENT:READ+IMPORT";
    public static final String PROJECT_ENVIRONMENT_READ_EXPORT = "PROJECT_ENVIRONMENT:READ+EXPORT";
    /*------ end: PROJECT_ENVIRONMENT ------*/

    /**
     * 项目版本权限
     */
    /*------ start: PROJECT_VERSION ------*/
    public static final String PROJECT_VERSION_READ = "PROJECT_VERSION:READ";
    public static final String PROJECT_VERSION_READ_ADD = "PROJECT_VERSION:READ+ADD";
    public static final String PROJECT_VERSION_READ_UPDATE = "PROJECT_VERSION:READ+UPDATE";
    public static final String PROJECT_VERSION_READ_DELETE = "PROJECT_VERSION:READ+DELETE";
    /*------ end: PROJECT_VERSION ------*/

    /**
     * 文件模块树
     * 查看文件：    项目管理-文件管理-查询权限
     * 添加文件：    项目管理-文件管理-创建权限
     * 编辑文件：    项目管理-文件管理-编辑权限
     * 下载文件：    项目管理-文件管理-下载权限
     * 删除文件：    项目管理-文件管理-删除权限
     */
    public static final String PROJECT_FILE_MANAGEMENT_READ = "PROJECT_FILE_MANAGEMENT:READ";
    public static final String PROJECT_FILE_MANAGEMENT_READ_ADD = "PROJECT_FILE_MANAGEMENT:READ+ADD";
    public static final String PROJECT_FILE_MANAGEMENT_READ_UPDATE = "PROJECT_FILE_MANAGEMENT:READ+UPDATE";
    public static final String PROJECT_FILE_MANAGEMENT_READ_DOWNLOAD = "PROJECT_FILE_MANAGEMENT:READ+DOWNLOAD";
    public static final String PROJECT_FILE_MANAGEMENT_READ_DELETE = "PROJECT_FILE_MANAGEMENT:READ+DELETE";

    /*------ start: PROJECT_CUSTOM_FUNCTION------*/
    public static final String PROJECT_CUSTOM_FUNCTION_READ = "PROJECT_CUSTOM_FUNCTION:READ";
    public static final String PROJECT_CUSTOM_FUNCTION_ADD = "PROJECT_CUSTOM_FUNCTION:READ+ADD";
    public static final String PROJECT_CUSTOM_FUNCTION_UPDATE = "PROJECT_CUSTOM_FUNCTION:READ+UPDATE";
    public static final String PROJECT_CUSTOM_FUNCTION_DELETE = "PROJECT_CUSTOM_FUNCTION:READ+DELETE";
    public static final String PROJECT_CUSTOM_FUNCTION_EXECUTE = "PROJECT_CUSTOM_FUNCTION:READ+EXECUTE";
    /*------ end: PROJECT_CUSTOM_FUNCTION ------*/

    /*------ start: PROJECT_TEMPLATE ------*/
    public static final String PROJECT_TEMPLATE_READ = "PROJECT_TEMPLATE:READ";
    public static final String PROJECT_TEMPLATE_ADD = "PROJECT_TEMPLATE:READ+ADD";
    public static final String PROJECT_TEMPLATE_UPDATE = "PROJECT_TEMPLATE:READ+UPDATE";
    public static final String PROJECT_TEMPLATE_DELETE = "PROJECT_TEMPLATE:READ+DELETE";
    /*------ end: PROJECT_TEMPLATE ------*/


    /*------ start: FUNCTIONAL_CASE ------*/
    public static final String FUNCTIONAL_CASE_READ = "FUNCTIONAL_CASE:READ";
    public static final String FUNCTIONAL_CASE_READ_ADD = "FUNCTIONAL_CASE:READ+ADD";
    public static final String FUNCTIONAL_CASE_READ_UPDATE = "FUNCTIONAL_CASE:READ+UPDATE";
    public static final String FUNCTIONAL_CASE_READ_DELETE = "FUNCTIONAL_CASE:READ+DELETE";
    public static final String FUNCTIONAL_CASE_READ_COMMENT = "FUNCTIONAL_CASE:READ+COMMENT";
    public static final String FUNCTIONAL_CASE_READ_EXPORT = "FUNCTIONAL_CASE:READ+EXPORT";
    public static final String FUNCTIONAL_CASE_READ_IMPORT = "FUNCTIONAL_CASE:READ+IMPORT";
    public static final String FUNCTIONAL_CASE_READ_MINDER = "FUNCTIONAL_CASE:READ+MINDER";
    public static final String FUNCTIONAL_CASE_PROJECT_TAB = "FUNCTIONAL_CASE_PROJECT_TAB";
    public static final String FUNCTIONAL_CASE_SYSTEM_TAB = "FUNCTIONAL_CASE_SYSTEM_TAB";
    public static final String FUNCTIONAL_CASE_WORKSPACE_READ = "FUNCTIONAL_CASE_WORKSPACE:READ";
    public static final String FUNCTIONAL_CASE_WORKSPACE_ADD = "FUNCTIONAL_CASE_WORKSPACE:ADD";
    public static final String FUNCTIONAL_CASE_WORKSPACE_UPDATE = "FUNCTIONAL_CASE_WORKSPACE:UPDATE";
    public static final String FUNCTIONAL_CASE_SYSTEM_CLASSIFY = "FUNCTIONAL_CASE_SYSTEM:CLASSIFY";
    /*------ start: CASE_ASSET (organization asset library, independent from project cases) ------*/
    public static final String CASE_ASSET_READ = "CASE_ASSET:READ";
    public static final String CASE_ASSET_ADD = "CASE_ASSET:READ+ADD";
    public static final String CASE_ASSET_UPDATE = "CASE_ASSET:READ+UPDATE";
    public static final String CASE_ASSET_DELETE = "CASE_ASSET:READ+DELETE";
    public static final String CASE_ASSET_IMPORT = "CASE_ASSET:READ+IMPORT";
    /*------ end: CASE_ASSET ------*/
    /*------ start: FUNCTIONAL_CASE_AI (独立 AI 生成用例权限) ------*/
    public static final String FUNCTIONAL_CASE_AI_READ = "FUNCTIONAL_CASE_AI:READ";
    public static final String FUNCTIONAL_CASE_AI_GENERATE = "FUNCTIONAL_CASE_AI:GENERATE";
    public static final String FUNCTIONAL_CASE_AI_UPLOAD = "FUNCTIONAL_CASE_AI:UPLOAD";
    public static final String FUNCTIONAL_CASE_AI_SAVE = "FUNCTIONAL_CASE_AI:SAVE";
    public static final String FUNCTIONAL_CASE_AI_REVIEW = "FUNCTIONAL_CASE_AI:REVIEW";
    public static final String FUNCTIONAL_CASE_AI_CONFIG = "FUNCTIONAL_CASE_AI:CONFIG";
    /*------ end: FUNCTIONAL_CASE_AI ------*/



    /*------ end: FUNCTIONAL_CASE ------*/

    /*------ start: CASE_REVIEW ------*/
    public static final String CASE_REVIEW_READ = "CASE_REVIEW:READ";
    public static final String CASE_REVIEW_READ_ADD = "CASE_REVIEW:READ+ADD";
    public static final String CASE_REVIEW_READ_UPDATE = "CASE_REVIEW:READ+UPDATE";
    public static final String CASE_REVIEW_READ_DELETE = "CASE_REVIEW:READ+DELETE";
    public static final String CASE_REVIEW_REVIEW = "CASE_REVIEW:READ+REVIEW";
    public static final String CASE_REVIEW_RELEVANCE = "CASE_REVIEW:READ+RELEVANCE";
    /*------ end: CASE_REVIEW ------*/

    /*------ start: API_DEBUG ------*/
    public static final String PROJECT_API_DEBUG_READ = "PROJECT_API_DEBUG:READ";
    public static final String PROJECT_API_DEBUG_ADD = "PROJECT_API_DEBUG:READ+ADD";
    public static final String PROJECT_API_DEBUG_UPDATE = "PROJECT_API_DEBUG:READ+UPDATE";
    public static final String PROJECT_API_DEBUG_DELETE = "PROJECT_API_DEBUG:READ+DELETE";
    public static final String PROJECT_API_DEBUG_IMPORT = "PROJECT_API_DEBUG:READ+IMPORT";
    public static final String PROJECT_API_DEBUG_EXECUTE = "PROJECT_API_DEBUG:READ+EXECUTE";
    /*------ end: API_DEBUG ------*/

    /*------ start: BUG ------*/
    public static final String PROJECT_BUG_READ = "PROJECT_BUG:READ";
    public static final String PROJECT_BUG_ADD = "PROJECT_BUG:READ+ADD";
    public static final String PROJECT_BUG_UPDATE = "PROJECT_BUG:READ+UPDATE";
    public static final String PROJECT_BUG_DELETE = "PROJECT_BUG:READ+DELETE";
    public static final String PROJECT_BUG_EXPORT = "PROJECT_BUG:READ+EXPORT";
    public static final String PROJECT_BUG_COMMENT = "PROJECT_BUG:READ+COMMENT";
    /*------ end: BUG ------*/

    /*------ start: AI_EXECUTION ------*/
    public static final String AI_EXECUTION_READ = "AI_EXECUTION:READ";
    public static final String AI_EXECUTION_RUN = "AI_EXECUTION:RUN";
    public static final String AI_EXECUTION_CANCEL = "AI_EXECUTION:CANCEL";
    public static final String AI_EXECUTION_LOGIN = "AI_EXECUTION:LOGIN";
    public static final String AI_EXECUTION_ADMIN = "AI_EXECUTION:ADMIN";
    /*------ end: AI_EXECUTION ------*/
    /*------ start: API_MANAGEMENT ------*/
    public static final String PROJECT_API_DEFINITION_READ = "PROJECT_API_DEFINITION:READ";
    public static final String PROJECT_API_DEFINITION_ADD = "PROJECT_API_DEFINITION:READ+ADD";
    public static final String PROJECT_API_DEFINITION_UPDATE = "PROJECT_API_DEFINITION:READ+UPDATE";
    public static final String PROJECT_API_DEFINITION_DELETE = "PROJECT_API_DEFINITION:READ+DELETE";
    public static final String PROJECT_API_DEFINITION_IMPORT = "PROJECT_API_DEFINITION:READ+IMPORT";
    public static final String PROJECT_API_DEFINITION_EXPORT = "PROJECT_API_DEFINITION:READ+EXPORT";
    public static final String PROJECT_API_DEFINITION_EXECUTE = "PROJECT_API_DEFINITION:READ+EXECUTE";
    public static final String PROJECT_API_DEFINITION_SHARE = "PROJECT_API_DEFINITION:READ+SHARE";
    public static final String PROJECT_API_DEFINITION_CASE_READ = "PROJECT_API_DEFINITION_CASE:READ";
    public static final String PROJECT_API_DEFINITION_CASE_ADD = "PROJECT_API_DEFINITION_CASE:READ+ADD";
    public static final String PROJECT_API_DEFINITION_CASE_UPDATE = "PROJECT_API_DEFINITION_CASE:READ+UPDATE";
    public static final String PROJECT_API_DEFINITION_CASE_DELETE = "PROJECT_API_DEFINITION_CASE:READ+DELETE";
    public static final String PROJECT_API_DEFINITION_CASE_EXECUTE = "PROJECT_API_DEFINITION_CASE:READ+EXECUTE";

    public static final String PROJECT_API_DEFINITION_MOCK_READ = "PROJECT_API_DEFINITION_MOCK:READ";
    public static final String PROJECT_API_DEFINITION_MOCK_ADD = "PROJECT_API_DEFINITION_MOCK:READ+ADD";
    public static final String PROJECT_API_DEFINITION_MOCK_UPDATE = "PROJECT_API_DEFINITION_MOCK:READ+UPDATE";
    public static final String PROJECT_API_DEFINITION_MOCK_DELETE = "PROJECT_API_DEFINITION_MOCK:READ+DELETE";
    public static final String PROJECT_API_DEFINITION_MOCK_EXECUTE = "PROJECT_API_DEFINITION_MOCK:READ+EXECUTE";

    public static final String PROJECT_API_DEFINITION_DOC_READ = "PROJECT_API_DEFINITION_DOC:READ";
    public static final String PROJECT_API_DEFINITION_DOC_SHARE = "PROJECT_API_DEFINITION_DOC:READ+SHARE";
    /* ----API_SCENARIO---- */
    public static final String PROJECT_API_SCENARIO_READ = "PROJECT_API_SCENARIO:READ";
    public static final String PROJECT_API_SCENARIO_ADD = "PROJECT_API_SCENARIO:READ+ADD";
    public static final String PROJECT_API_SCENARIO_UPDATE = "PROJECT_API_SCENARIO:READ+UPDATE";
    public static final String PROJECT_API_SCENARIO_DELETE = "PROJECT_API_SCENARIO:READ+DELETE";
    public static final String PROJECT_API_SCENARIO_EXECUTE = "PROJECT_API_SCENARIO:READ+EXECUTE";
    public static final String PROJECT_API_SCENARIO_IMPORT = "PROJECT_API_SCENARIO:READ+IMPORT";
    public static final String PROJECT_API_SCENARIO_EXPORT = "PROJECT_API_SCENARIO:READ+EXPORT";


    /*------ end: API_MANAGEMENT ------*/

    /*------ start: API_REPORT ------*/
    public static final String PROJECT_API_REPORT_READ = "PROJECT_API_REPORT:READ";
    public static final String PROJECT_API_REPORT_UPDATE = "PROJECT_API_REPORT:READ+UPDATE";
    public static final String PROJECT_API_REPORT_DELETE = "PROJECT_API_REPORT:READ+DELETE";
    public static final String PROJECT_API_REPORT_SHARE = "PROJECT_API_REPORT:READ+SHARE";
    public static final String PROJECT_API_REPORT_EXPORT = "PROJECT_API_REPORT:READ+EXPORT";
    /*------ end: API_REPORT ------*/

    //个人中心
    /*------ start: PERSONAL_CENTER ------*/
    public static final String SYSTEM_PERSONAL_API_KEY_ADD = "SYSTEM_PERSONAL_API_KEY:READ+ADD";
    public static final String SYSTEM_PERSONAL_API_KEY_DELETE = "SYSTEM_PERSONAL_API_KEY:READ+DELETE";
    public static final String SYSTEM_PERSONAL_API_KEY_READ = "SYSTEM_PERSONAL_API_KEY:READ";
    public static final String SYSTEM_PERSONAL_API_KEY_UPDATE = "SYSTEM_PERSONAL_API_KEY:READ+UPDATE";
    public static final String SYSTEM_PERSONAL_AI_AGENT_READ = "SYSTEM_PERSONAL_AI_AGENT:READ";
    public static final String SYSTEM_PERSONAL_AI_AGENT_CONNECT = "SYSTEM_PERSONAL_AI_AGENT:READ+CONNECT";
    public static final String SYSTEM_PERSONAL_AI_AGENT_REVOKE = "SYSTEM_PERSONAL_AI_AGENT:READ+REVOKE";
    /*------ end: PERSONAL_CENTER ------*/

    //测试计划
    /*------ start: TEST_PLAN ------*/

    public static final String TEST_PLAN_READ = "PROJECT_TEST_PLAN:READ";
    public static final String TEST_PLAN_READ_ADD = "PROJECT_TEST_PLAN:READ+ADD";
    public static final String TEST_PLAN_READ_UPDATE = "PROJECT_TEST_PLAN:READ+UPDATE";
    public static final String TEST_PLAN_READ_DELETE = "PROJECT_TEST_PLAN:READ+DELETE";
    public static final String TEST_PLAN_READ_EXECUTE = "PROJECT_TEST_PLAN:READ+EXECUTE";
    public static final String TEST_PLAN_READ_ASSOCIATION = "PROJECT_TEST_PLAN:READ+ASSOCIATION";

    public static final String TEST_PLAN_REPORT_READ = "PROJECT_TEST_PLAN_REPORT:READ";
    public static final String TEST_PLAN_REPORT_READ_UPDATE = "PROJECT_TEST_PLAN_REPORT:READ+UPDATE";
    public static final String TEST_PLAN_REPORT_READ_SHARE = "PROJECT_TEST_PLAN_REPORT:READ+SHARE";
    public static final String TEST_PLAN_REPORT_READ_DELETE = "PROJECT_TEST_PLAN_REPORT:READ+DELETE";
    public static final String TEST_PLAN_REPORT_READ_EXPORT = "PROJECT_TEST_PLAN_REPORT:READ+EXPORT";
    public static final String TEST_PLAN_REVIEW_TAB = "TEST_PLAN_REVIEW_TAB";
    public static final String TEST_PLAN_TEST_REPORT_TAB = "TEST_PLAN_TEST_REPORT_TAB";
    public static final String PROJECT_LIST_PAGE = "PROJECT_LIST_PAGE";
    public static final String PROJECT_DETAIL_PAGE = "PROJECT_DETAIL_PAGE";
    public static final String PROJECT_SWITCH = "PROJECT_SWITCH";
    public static final String SYSTEM_CONFIG_WECOM_BOT_READ = "SYSTEM_CONFIG_WECOM_BOT:READ";
    public static final String SYSTEM_CONFIG_WECOM_BOT_UPDATE = "SYSTEM_CONFIG_WECOM_BOT:UPDATE";
    public static final String SYSTEM_NOTIFICATION_RULE_READ = "SYSTEM_NOTIFICATION_RULE:READ";
    public static final String SYSTEM_NOTIFICATION_RULE_CREATE = "SYSTEM_NOTIFICATION_RULE:CREATE";
    public static final String SYSTEM_NOTIFICATION_RULE_UPDATE = "SYSTEM_NOTIFICATION_RULE:UPDATE";
    public static final String SYSTEM_NOTIFICATION_RULE_DELETE = "SYSTEM_NOTIFICATION_RULE:DELETE";
    public static final String SYSTEM_NOTIFICATION_LOG_READ = "SYSTEM_NOTIFICATION_LOG:READ";
    public static final String SYSTEM_NOTIFICATION_LOG_RETRY = "SYSTEM_NOTIFICATION_LOG:RETRY";
    /*------ end: TEST_PLAN ------*/

    /*------ start: SYSTEM_TASK_CENTER ------*/
    public static final String SYSTEM_TASK_CENTER_READ = "SYSTEM_TASK_CENTER:READ";
    public static final String SYSTEM_TASK_CENTER_READ_STOP = "SYSTEM_TASK_CENTER:READ+STOP";

    //用例执行任务
    public static final String SYSTEM_CASE_TASK_CENTER_READ = "SYSTEM_CASE_TASK_CENTER:READ";
    public static final String SYSTEM_CASE_TASK_CENTER_EXEC_STOP = "SYSTEM_CASE_TASK_CENTER:EXEC+STOP";
    public static final String SYSTEM_CASE_TASK_CENTER_DELETE = "SYSTEM_CASE_TASK_CENTER:READ+DELETE";
    //后台任务
    public static final String SYSTEM_SCHEDULE_TASK_CENTER_READ = "SYSTEM_SCHEDULE_TASK_CENTER:READ";
    public static final String SYSTEM_SCHEDULE_TASK_CENTER_READ_UPDATE = "SYSTEM_SCHEDULE_TASK_CENTER:READ+UPDATE";
    public static final String SYSTEM_SCHEDULE_TASK_CENTER_READ_DELETE = "SYSTEM_SCHEDULE_TASK_CENTER:READ+DELETE";
    /*------ end: SYSTEM_TASK_CENTER ------*/

    /*------ start: ORGANIZATION_TASK_CENTER_READ ------*/
    public static final String ORGANIZATION_TASK_CENTER_READ = "ORGANIZATION_TASK_CENTER:READ";
    public static final String ORGANIZATION_TASK_CENTER_READ_STOP = "ORGANIZATION_TASK_CENTER:READ+STOP";

    public static final String ORGANIZATION_CASE_TASK_CENTER_READ = "ORGANIZATION_CASE_TASK_CENTER:READ";
    public static final String ORGANIZATION_CASE_TASK_CENTER_EXEC_STOP = "ORGANIZATION_CASE_TASK_CENTER:EXEC+STOP";
    public static final String ORGANIZATION_CASE_TASK_CENTER_DELETE = "ORGANIZATION_CASE_TASK_CENTER:READ+DELETE";
    //后台任务
    public static final String ORGANIZATION_SCHEDULE_TASK_CENTER_READ = "ORGANIZATION_SCHEDULE_TASK_CENTER:READ";
    public static final String ORGANIZATION_SCHEDULE_TASK_CENTER_READ_UPDATE = "ORGANIZATION_SCHEDULE_TASK_CENTER:READ+UPDATE";
    public static final String ORGANIZATION_SCHEDULE_TASK_CENTER_READ_DELETE = "ORGANIZATION_SCHEDULE_TASK_CENTER:READ+DELETE";

    /*------ end: ORGANIZATION_TASK_CENTER_READ ------*/

    /*------ start: PROJECT_TASK_CENTER_READ ------*/
    public static final String PROJECT_CASE_TASK_CENTER_READ = "PROJECT_CASE_TASK_CENTER:READ";
    public static final String PROJECT_CASE_TASK_CENTER_EXEC_STOP = "PROJECT_CASE_TASK_CENTER:EXEC+STOP";
    public static final String PROJECT_CASE_TASK_CENTER_DELETE = "PROJECT_CASE_TASK_CENTER:READ+DELETE";
    public static final String PROJECT_SCHEDULE_TASK_CENTER_READ = "PROJECT_SCHEDULE_TASK_CENTER:READ";
    public static final String PROJECT_SCHEDULE_TASK_CENTER_READ_UPDATE = "PROJECT_SCHEDULE_TASK_CENTER:READ+UPDATE";
    public static final String PROJECT_SCHEDULE_TASK_CENTER_READ_DELETE = "PROJECT_SCHEDULE_TASK_CENTER:READ+DELETE";
    /*------ end: PROJECT_TASK_CENTER_READ ------*/
}
