package io.metersphere.agent.constants;

public enum AgentBusinessVerdict {
    PASSED, PRODUCT_FAILED, ENV_FAILED, DATA_FAILED, AUTH_FAILED, LOCATOR_FAILED,
    ASSERTION_FAILED, AGENT_PLAN_FAILED, AGENT_FAILED, RUNNER_FAILED, BLOCKED,
    NEEDS_REVIEW, CANCELED
}
