package io.metersphere.agent.service;
import io.metersphere.agent.dto.*;import io.metersphere.sdk.exception.MSException;import io.metersphere.sdk.util.JSON;import io.metersphere.system.uid.IDGenerator;import io.metersphere.system.utils.SessionUtils;import jakarta.annotation.Resource;import org.apache.commons.lang3.StringUtils;import org.springframework.dao.DuplicateKeyException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service public class AgentBusinessFlowService {@Resource private JdbcTemplate jdbc;@Resource private AgentProjectService projects;@Resource private TestAssetVersionService versions;private static final Set<String>ACTIONS=Set.of("NAVIGATE","CLICK","FILL","SELECT","WAIT","ASSERT","UPLOAD","KEYBOARD");
 public List<AgentBusinessFlowDTO> list(String projectId){String p=projects.resolveProjectId(projectId);return jdbc.query("SELECT * FROM ai_business_flow WHERE project_id=? ORDER BY update_time DESC",this::map,p).stream().map(this::withVersion).toList();}
 public AgentBusinessFlowDTO get(String id){List<AgentBusinessFlowDTO>r=jdbc.query("SELECT * FROM ai_business_flow WHERE id=?",this::map,id);if(r.isEmpty())throw new MSException("BUSINESS_FLOW_NOT_FOUND");projects.resolveProjectId(r.getFirst().getProjectId());return withVersion(r.getFirst());}
 public AgentBusinessFlowDTO get(String projectId,String id){String resolved=projects.resolveProjectId(projectId);AgentBusinessFlowDTO value=get(id);if(!resolved.equals(value.getProjectId()))throw new MSException("BUSINESS_FLOW_PROJECT_MISMATCH");return value;}
 @Transactional(rollbackFor=Exception.class) public AgentBusinessFlowDTO create(AgentBusinessFlowRequest r){String p=projects.resolveProjectId(r.getProjectId());validate(r);String org=jdbc.queryForObject("SELECT organization_id FROM project WHERE id=?",String.class,p),id=IDGenerator.nextStr();long now=System.currentTimeMillis();try{jdbc.update("INSERT INTO ai_business_flow(id,organization_id,project_id,name,nodes_json,edges_json,entry_node_id,exit_conditions,allowed_actions,status,version,create_user,update_user,create_time,update_time) VALUES (?,?,?,?,?,?,?,?,?,?,0,?,?,?,?,?)",id,org,p,r.getName().trim(),JSON.toJSONString(r.getNodes()),JSON.toJSONString(r.getEdges()),r.getEntryNodeId(),JSON.toJSONString(r.getExitConditions()),JSON.toJSONString(normalizeActions(r.getAllowedActions())),status(r.getStatus()),SessionUtils.getUserId(),SessionUtils.getUserId(),now,now);}catch(DuplicateKeyException e){throw new MSException("BUSINESS_FLOW_NAME_CONFLICT");}return publishIfNeeded(get(id));}
 @Transactional(rollbackFor=Exception.class) public AgentBusinessFlowDTO update(String id,AgentBusinessFlowRequest r){AgentBusinessFlowDTO old=get(id);String p=projects.resolveProjectId(r.getProjectId());if(!p.equals(old.getProjectId()))throw new MSException("BUSINESS_FLOW_PROJECT_MISMATCH");validate(r);int expected=r.getVersion()==null?old.getVersion():r.getVersion();if(jdbc.update("UPDATE ai_business_flow SET name=?,nodes_json=?,edges_json=?,entry_node_id=?,exit_conditions=?,allowed_actions=?,status=?,version=version+1,update_user=?,update_time=? WHERE id=? AND version=?",r.getName().trim(),JSON.toJSONString(r.getNodes()),JSON.toJSONString(r.getEdges()),r.getEntryNodeId(),JSON.toJSONString(r.getExitConditions()),JSON.toJSONString(normalizeActions(r.getAllowedActions())),status(r.getStatus()),SessionUtils.getUserId(),System.currentTimeMillis(),id,expected)!=1)throw new MSException("BUSINESS_FLOW_VERSION_CONFLICT");return publishIfNeeded(get(id));}
 private void validate(AgentBusinessFlowRequest r){Set<String>ids=new HashSet<>();for(Map<String,Object>n:r.getNodes()){String id=String.valueOf(n.get("id"));if(StringUtils.isBlank(id)||!ids.add(id))throw new MSException("BUSINESS_FLOW_NODE_ID_INVALID");}if(!ids.contains(r.getEntryNodeId()))throw new MSException("BUSINESS_FLOW_ENTRY_NODE_INVALID");for(Map<String,Object>e:r.getEdges())if(!ids.contains(String.valueOf(e.get("source")))||!ids.contains(String.valueOf(e.get("target"))))throw new MSException("BUSINESS_FLOW_EDGE_INVALID");normalizeActions(r.getAllowedActions());}
 private List<String>normalizeActions(List<String>a){List<String>v=a.stream().map(StringUtils::upperCase).distinct().sorted().toList();if(!ACTIONS.containsAll(v))throw new MSException("BUSINESS_FLOW_ACTION_INVALID");return v;}private String status(String s){String v=StringUtils.defaultIfBlank(s,"DRAFT").toUpperCase();if(!Set.of("DRAFT","PUBLISHED","DISABLED").contains(v))throw new MSException("BUSINESS_FLOW_STATUS_INVALID");return v;}
 private AgentBusinessFlowDTO publishIfNeeded(AgentBusinessFlowDTO d){if(!"PUBLISHED".equals(d.getStatus()))return d;var v=versions.publish(d.getProjectId(),"BUSINESS_FLOW",d.getId(),String.valueOf(d.getVersion()),JSON.toJSONString(d),SessionUtils.getUserId());d.setAssetVersionId(v.getId());return d;}private AgentBusinessFlowDTO withVersion(AgentBusinessFlowDTO d){try{if("PUBLISHED".equals(d.getStatus()))d.setAssetVersionId(versions.latestPublished(d.getProjectId(),"BUSINESS_FLOW",d.getId()).getId());}catch(MSException ignored){}return d;}
 private AgentBusinessFlowDTO map(java.sql.ResultSet r,int n)throws java.sql.SQLException{AgentBusinessFlowDTO d=new AgentBusinessFlowDTO();d.setId(r.getString("id"));d.setOrganizationId(r.getString("organization_id"));d.setProjectId(r.getString("project_id"));d.setName(r.getString("name"));d.setNodes(JSON.parseObject(r.getString("nodes_json"),new com.fasterxml.jackson.core.type.TypeReference<List<Map<String,Object>>>(){}));d.setEdges(JSON.parseObject(r.getString("edges_json"),new com.fasterxml.jackson.core.type.TypeReference<List<Map<String,Object>>>(){}));d.setEntryNodeId(r.getString("entry_node_id"));d.setExitConditions(JSON.parseObject(r.getString("exit_conditions"),new com.fasterxml.jackson.core.type.TypeReference<List<Map<String,Object>>>(){}));d.setAllowedActions(JSON.parseArray(r.getString("allowed_actions"),String.class));d.setStatus(r.getString("status"));d.setVersion(r.getInt("version"));d.setCreateTime(r.getLong("create_time"));d.setUpdateTime(r.getLong("update_time"));return d;}}
