package io.metersphere.agent.service;
import io.metersphere.agent.dto.*;import io.metersphere.sdk.exception.MSException;import io.metersphere.sdk.util.JSON;import io.metersphere.system.uid.IDGenerator;import io.metersphere.system.utils.SessionUtils;import jakarta.annotation.Resource;import org.apache.commons.lang3.StringUtils;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.net.URI;import java.util.*;
@Service public class AgentPageObjectService {@Resource private JdbcTemplate jdbc;@Resource private AgentProjectService projects;@Resource private AgentWebExecutionContractValidator validator;@Resource private TestAssetVersionService versions;
 public List<AgentPageObjectDTO> list(String projectId){String p=projects.resolveProjectId(projectId);return jdbc.query("SELECT * FROM ai_page_object WHERE project_id=? ORDER BY update_time DESC",this::map,p).stream().map(this::withElements).toList();}
 public AgentPageObjectDTO get(String id){List<AgentPageObjectDTO> rows=jdbc.query("SELECT * FROM ai_page_object WHERE id=?",this::map,id);if(rows.isEmpty())throw new MSException("PAGE_OBJECT_NOT_FOUND");projects.resolveProjectId(rows.getFirst().getProjectId());return withElements(rows.getFirst());}
 public AgentPageObjectDTO get(String projectId,String id){String resolved=projects.resolveProjectId(projectId);AgentPageObjectDTO value=get(id);if(!resolved.equals(value.getProjectId()))throw new MSException("PAGE_OBJECT_PROJECT_MISMATCH");return value;}
 @Transactional(rollbackFor=Exception.class) public AgentPageObjectDTO create(AgentPageObjectRequest r){String p=projects.resolveProjectId(r.getProjectId());validate(r);String org=jdbc.queryForObject("SELECT organization_id FROM project WHERE id=?",String.class,p);String id=IDGenerator.nextStr();long now=System.currentTimeMillis();jdbc.update("INSERT INTO ai_page_object(id,organization_id,project_id,name,route_pattern,allowed_origins,status,version,create_user,update_user,create_time,update_time) VALUES (?,?,?,?,?,?,?,0,?,?,?,?)",id,org,p,r.getName().trim(),StringUtils.trimToNull(r.getRoutePattern()),JSON.toJSONString(origins(r.getAllowedOrigins())),normalizeStatus(r.getStatus()),SessionUtils.getUserId(),SessionUtils.getUserId(),now,now);replaceElements(id,r.getElements(),now);return publishIfNeeded(get(id));}
 @Transactional(rollbackFor=Exception.class) public AgentPageObjectDTO update(String id,AgentPageObjectRequest r){AgentPageObjectDTO old=get(id);String p=projects.resolveProjectId(r.getProjectId());if(!p.equals(old.getProjectId()))throw new MSException("PAGE_OBJECT_PROJECT_MISMATCH");validate(r);long now=System.currentTimeMillis();if(jdbc.update("UPDATE ai_page_object SET name=?,route_pattern=?,allowed_origins=?,status=?,version=version+1,update_user=?,update_time=? WHERE id=? AND version=?",r.getName().trim(),StringUtils.trimToNull(r.getRoutePattern()),JSON.toJSONString(origins(r.getAllowedOrigins())),normalizeStatus(r.getStatus()),SessionUtils.getUserId(),now,id,r.getVersion())!=1)throw new MSException("PAGE_OBJECT_VERSION_CONFLICT");jdbc.update("DELETE FROM ai_page_element WHERE page_object_id=?",id);replaceElements(id,r.getElements(),now);return publishIfNeeded(get(id));}
 public AgentWebLocatorDTO resolveLocator(String pageObjectId,String elementName){AgentPageObjectDTO page=get(pageObjectId);if(!"PUBLISHED".equals(page.getStatus()))throw new MSException("PUBLISHED_PAGE_OBJECT_REQUIRED");AgentPageElementDTO element=page.getElements().stream().filter(e->elementName.equals(e.getName())).findFirst().orElseThrow(()->new MSException("PAGE_ELEMENT_NOT_FOUND"));return locator(element.getStrategy(),element.getSelectorValue());}
 private AgentPageObjectDTO publishIfNeeded(AgentPageObjectDTO d){if("PUBLISHED".equals(d.getStatus()))versions.publish(d.getProjectId(),"PAGE_OBJECT",d.getId(),String.valueOf(d.getVersion()),JSON.toJSONString(d),SessionUtils.getUserId());return d;}
 private void replaceElements(String pageId,List<AgentPageElementRequest> elements,long now){for(AgentPageElementRequest e:elements==null?List.<AgentPageElementRequest>of():elements){validateElement(e);jdbc.update("INSERT INTO ai_page_element(id,page_object_id,name,strategy,selector_value,fallback_locators,sensitive,risk_level,version,create_user,update_user,create_time,update_time) VALUES (?,?,?,?,?,?,?,?,0,?,?,?,?)",IDGenerator.nextStr(),pageId,e.getName().trim(),e.getStrategy().toUpperCase(),e.getSelectorValue(),normalizeFallback(e.getFallbackLocators()),Boolean.TRUE.equals(e.getSensitive()),StringUtils.defaultIfBlank(e.getRiskLevel(),"LOW").toUpperCase(),SessionUtils.getUserId(),SessionUtils.getUserId(),now,now);}}
 private void validate(AgentPageObjectRequest r){if(r.getElements()==null||r.getElements().isEmpty())throw new MSException("PAGE_OBJECT_ELEMENT_REQUIRED");Set<String> names=new HashSet<>();for(AgentPageElementRequest e:r.getElements()){if(!names.add(e.getName().trim()))throw new MSException("PAGE_ELEMENT_NAME_DUPLICATE");validateElement(e);}origins(r.getAllowedOrigins());}
 private void validateElement(AgentPageElementRequest e){AgentWebLocatorDTO l=locator(e.getStrategy(),e.getSelectorValue());validator.validateLocator(l);if(StringUtils.isNotBlank(e.getFallbackLocators()))for(AgentWebLocatorDTO f:JSON.parseArray(e.getFallbackLocators(),AgentWebLocatorDTO.class))validator.validateLocator(f);if(!Set.of("LOW","HIGH").contains(StringUtils.defaultIfBlank(e.getRiskLevel(),"LOW").toUpperCase()))throw new MSException("PAGE_ELEMENT_RISK_INVALID");}
 private AgentWebLocatorDTO locator(String strategy,String value){AgentWebLocatorDTO l=new AgentWebLocatorDTO();l.setStrategy(strategy);switch(strategy.toUpperCase()){case"TEST_ID"->l.setTestId(value);case"LABEL"->l.setLabel(value);case"PLACEHOLDER"->l.setPlaceholder(value);case"TEXT"->l.setText(value);case"CSS"->l.setSelector(value);case"ROLE"->{String[]v=value.split("\\|",2);if(v.length!=2)throw new MSException("ROLE_SELECTOR_MUST_BE_ROLE_PIPE_NAME");l.setRole(v[0]);l.setName(v[1]);}default->throw new MSException("PAGE_ELEMENT_STRATEGY_INVALID");}return l;}
 private List<String> origins(List<String> values){List<String> out=new ArrayList<>();for(String value:values==null?List.<String>of():values){URI u=URI.create(value);if(!"https".equalsIgnoreCase(u.getScheme())||u.getHost()==null)throw new MSException("PAGE_OBJECT_ORIGIN_INVALID");out.add(u.getScheme()+"://"+u.getAuthority());}return out.stream().distinct().sorted().toList();}
 private String normalizeFallback(String v){return StringUtils.isBlank(v)?null:JSON.toJSONString(JSON.parseArray(v));}private String normalizeStatus(String s){String v=StringUtils.defaultIfBlank(s,"DRAFT").toUpperCase();if(!Set.of("DRAFT","PUBLISHED","DISABLED").contains(v))throw new MSException("PAGE_OBJECT_STATUS_INVALID");return v;}
 private AgentPageObjectDTO withElements(AgentPageObjectDTO d){d.setElements(jdbc.query("SELECT * FROM ai_page_element WHERE page_object_id=? ORDER BY create_time,id",(r,n)->{AgentPageElementDTO e=new AgentPageElementDTO();e.setId(r.getString("id"));e.setPageObjectId(r.getString("page_object_id"));e.setName(r.getString("name"));e.setStrategy(r.getString("strategy"));e.setSelectorValue(r.getString("selector_value"));e.setFallbackLocators(r.getString("fallback_locators"));e.setSensitive(r.getBoolean("sensitive"));e.setRiskLevel(r.getString("risk_level"));e.setVersion(r.getInt("version"));e.setCreateTime(r.getLong("create_time"));e.setUpdateTime(r.getLong("update_time"));return e;},d.getId()));return d;}
 private AgentPageObjectDTO map(java.sql.ResultSet r,int n)throws java.sql.SQLException{AgentPageObjectDTO d=new AgentPageObjectDTO();d.setId(r.getString("id"));d.setOrganizationId(r.getString("organization_id"));d.setProjectId(r.getString("project_id"));d.setName(r.getString("name"));d.setRoutePattern(r.getString("route_pattern"));d.setAllowedOrigins(JSON.parseArray(r.getString("allowed_origins"),String.class));d.setStatus(r.getString("status"));d.setVersion(r.getInt("version"));d.setCreateTime(r.getLong("create_time"));d.setUpdateTime(r.getLong("update_time"));return d;}}
