package io.metersphere.agent.service;
import io.metersphere.sdk.exception.MSException;import io.metersphere.system.uid.IDGenerator;import io.metersphere.sdk.util.LogUtils;import jakarta.annotation.Resource;import org.apache.commons.lang3.StringUtils;import org.springframework.beans.factory.annotation.Value;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service public class AgentTestDataCleanupService {
 @Resource private JdbcTemplate jdbc; private final List<AgentTestDataCleanupHandler> handlers;
 @Value("${agent.execution.data-cleanup-max-attempts:5}") private int maxAttempts;
 public AgentTestDataCleanupService(Optional<List<AgentTestDataCleanupHandler>> handlers){this.handlers=handlers.orElseGet(List::of);}
 @Transactional(rollbackFor=Exception.class) public String enqueue(String leaseId,String cleanupType){String type=StringUtils.upperCase(StringUtils.defaultIfBlank(cleanupType,"DATASET"));Integer exists=jdbc.queryForObject("SELECT COUNT(1) FROM ai_test_data_cleanup WHERE lease_id=? AND cleanup_type=? AND status IN ('PENDING','RUNNING','SUCCESS')",Integer.class,leaseId,type);if(exists!=null&&exists>0)return jdbc.queryForObject("SELECT id FROM ai_test_data_cleanup WHERE lease_id=? AND cleanup_type=? ORDER BY created_at DESC LIMIT 1",String.class,leaseId,type);String id=IDGenerator.nextStr();jdbc.update("INSERT INTO ai_test_data_cleanup(id,lease_id,cleanup_type,status,attempt_count,next_retry_at,created_at) VALUES (?,?,?,'PENDING',0,?,?)",id,leaseId,type,System.currentTimeMillis(),System.currentTimeMillis());return id;}
 @Transactional(rollbackFor=Exception.class) public void execute(String id){Map<String,Object> job=jdbc.queryForMap("SELECT c.*,l.task_id,l.execution_id,l.dataset_id,l.data_key,l.namespace FROM ai_test_data_cleanup c JOIN ai_test_data_lease l ON l.id=c.lease_id WHERE c.id=? FOR UPDATE",id);if("SUCCESS".equals(job.get("status")))return;String type=(String)job.get("cleanup_type");jdbc.update("UPDATE ai_test_data_cleanup SET status='RUNNING',attempt_count=attempt_count+1 WHERE id=?",id);try{AgentTestDataCleanupHandler handler=handlers.stream().filter(h->h.supports(type)).findFirst().orElseThrow(()->new MSException("TEST_DATA_CLEANUP_HANDLER_NOT_CONFIGURED"));handler.cleanup((String)job.get("lease_id"),(String)job.get("task_id"),(String)job.get("execution_id"),(String)job.get("dataset_id"),(String)job.get("data_key"),(String)job.get("namespace"));jdbc.update("UPDATE ai_test_data_cleanup SET status='SUCCESS',finished_at=?,error_code=NULL,error_message=NULL WHERE id=?",System.currentTimeMillis(),id);}catch(RuntimeException ex){markFailed(id,ex);}}
 public void markFailed(String id,Throwable error){Integer attempts=jdbc.queryForObject("SELECT attempt_count FROM ai_test_data_cleanup WHERE id=?",Integer.class,id);boolean terminal=attempts!=null&&attempts>=maxAttempts;long next=System.currentTimeMillis()+(1L<<Math.min(attempts==null?1:attempts,10))*1000L;jdbc.update("UPDATE ai_test_data_cleanup SET status=?,next_retry_at=?,error_code='TEST_DATA_CLEANUP_FAILED',error_message='Test data cleanup failed',finished_at=? WHERE id=?",terminal?"FAILED":"PENDING",terminal?null:next,terminal?System.currentTimeMillis():null,id);LogUtils.error("AI test data cleanup failed, cleanupId={}",id,error);}
 @Scheduled(fixedDelayString="${agent.execution.data-cleanup-scan-ms:30000}") public void retryDue(){for(String id:jdbc.queryForList("SELECT id FROM ai_test_data_cleanup WHERE status='PENDING' AND (next_retry_at IS NULL OR next_retry_at<=?) ORDER BY created_at LIMIT 100",String.class,System.currentTimeMillis()))try{execute(id);}catch(RuntimeException ex){markFailed(id,ex);}}
}
