package io.metersphere.agent.service;
import io.metersphere.agent.dto.*;import io.metersphere.sdk.exception.MSException;import io.metersphere.sdk.util.JSON;import io.metersphere.system.uid.IDGenerator;import io.metersphere.system.utils.SessionUtils;import jakarta.annotation.Resource;import org.apache.commons.codec.digest.DigestUtils;import org.apache.commons.lang3.StringUtils;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service public class AgentPromptTemplateService {
 @Resource private JdbcTemplate jdbc; @Resource private AgentProjectService projects;
 public List<AgentPromptTemplateVersionDTO> list(String projectId,String templateId){String org=organization(projectId);return jdbc.query("SELECT * FROM ai_prompt_template_version WHERE organization_id=? AND (? IS NULL OR prompt_template_id=?) ORDER BY create_time DESC",this::map,org,StringUtils.trimToNull(templateId),StringUtils.trimToNull(templateId));}
 @Transactional(rollbackFor=Exception.class) public AgentPromptTemplateVersionDTO create(AgentPromptTemplateVersionRequest r){String org=organization(r.getProjectId());validateJson(r.getVariableSchema());String template=StringUtils.defaultIfBlank(r.getPromptTemplateId(),IDGenerator.nextStr());Integer version=jdbc.queryForObject("SELECT COALESCE(MAX(version_no),0)+1 FROM ai_prompt_template_version WHERE organization_id=? AND prompt_template_id=?",Integer.class,org,template);long now=System.currentTimeMillis();String id=IDGenerator.nextStr();String hash=DigestUtils.sha256Hex(r.getSystemTemplate()+"\n"+r.getBusinessTemplate()+"\n"+normalize(r.getVariableSchema())+"\n"+r.getOutputSchemaVersion());jdbc.update("INSERT INTO ai_prompt_template_version(id,prompt_template_id,organization_id,name,version_no,system_template,business_template,variable_schema,output_schema_version,content_hash,status,create_user,create_time) VALUES (?,?,?,?,?,?,?,?,?,?,'DRAFT',?,?)",id,template,org,r.getName().trim(),version,r.getSystemTemplate(),r.getBusinessTemplate(),normalize(r.getVariableSchema()),r.getOutputSchemaVersion(),hash,SessionUtils.getUserId(),now);return get(id,r.getProjectId());}
 @Transactional(rollbackFor=Exception.class) public AgentPromptTemplateVersionDTO publish(String id,String projectId){AgentPromptTemplateVersionDTO p=get(id,projectId);if(!"DRAFT".equals(p.getStatus()))throw new MSException("PROMPT_VERSION_NOT_DRAFT");long now=System.currentTimeMillis();jdbc.update("UPDATE ai_prompt_template_version SET status='ARCHIVED' WHERE organization_id=? AND prompt_template_id=? AND status='PUBLISHED'",p.getOrganizationId(),p.getPromptTemplateId());if(jdbc.update("UPDATE ai_prompt_template_version SET status='PUBLISHED',published_by=?,published_at=? WHERE id=? AND status='DRAFT'",SessionUtils.getUserId(),now,id)!=1)throw new MSException("PROMPT_VERSION_PUBLISH_CONFLICT");return get(id,projectId);}
 public Map<String,Object> preview(String id,String projectId,Map<String,Object> variables){AgentPromptTemplateVersionDTO p=get(id,projectId);Map<String,Object> safe=variables==null?Map.of():variables;String system=render(p.getSystemTemplate(),safe);String business=render(p.getBusinessTemplate(),safe);return Map.of("versionId",p.getId(),"contentHash",p.getContentHash(),"systemPrompt",system,"businessPrompt",business);}
 @Transactional(rollbackFor=Exception.class) public AgentPromptTemplateVersionDTO rollback(String id,String projectId){AgentPromptTemplateVersionDTO source=get(id,projectId);AgentPromptTemplateVersionRequest r=new AgentPromptTemplateVersionRequest();r.setProjectId(projectId);r.setPromptTemplateId(source.getPromptTemplateId());r.setName(source.getName()+" rollback v"+source.getVersionNo());r.setSystemTemplate(source.getSystemTemplate());r.setBusinessTemplate(source.getBusinessTemplate());r.setVariableSchema(source.getVariableSchema());r.setOutputSchemaVersion(source.getOutputSchemaVersion());return create(r);}
 public AgentPromptTemplateVersionDTO resolvePublished(String templateId,String projectId){String org=organization(projectId);List<AgentPromptTemplateVersionDTO> rows=jdbc.query("SELECT * FROM ai_prompt_template_version WHERE organization_id=? AND prompt_template_id=? AND status='PUBLISHED' ORDER BY version_no DESC LIMIT 1",this::map,org,templateId);if(rows.isEmpty())throw new MSException("PUBLISHED_PROMPT_TEMPLATE_REQUIRED");return rows.getFirst();}
 public String freeze(AgentPromptTemplateVersionDTO p){Map<String,Object> out=new LinkedHashMap<>();out.put("id",p.getId());out.put("promptTemplateId",p.getPromptTemplateId());out.put("versionNo",p.getVersionNo());out.put("name",p.getName());out.put("systemTemplate",p.getSystemTemplate());out.put("businessTemplate",p.getBusinessTemplate());out.put("variableSchema",JSON.parseObject(p.getVariableSchema()));out.put("outputSchemaVersion",p.getOutputSchemaVersion());out.put("contentHash",p.getContentHash());return JSON.toJSONString(out);}
 private AgentPromptTemplateVersionDTO get(String id,String projectId){String org=organization(projectId);List<AgentPromptTemplateVersionDTO> rows=jdbc.query("SELECT * FROM ai_prompt_template_version WHERE id=? AND organization_id=?",this::map,id,org);if(rows.isEmpty())throw new MSException("PROMPT_VERSION_NOT_FOUND");return rows.getFirst();}
 private String organization(String projectId){String p=projects.resolveProjectId(projectId);return jdbc.queryForObject("SELECT organization_id FROM project WHERE id=?",String.class,p);}
 private String render(String template,Map<String,Object> values){String result=StringUtils.defaultString(template);java.util.regex.Matcher matcher=java.util.regex.Pattern.compile("\\{\\{([A-Za-z0-9_.-]+)}}").matcher(result);StringBuffer out=new StringBuffer();while(matcher.find()){Object value=values.get(matcher.group(1));if(value==null)throw new MSException("PROMPT_VARIABLE_MISSING: "+matcher.group(1));matcher.appendReplacement(out,java.util.regex.Matcher.quoteReplacement(String.valueOf(value)));}matcher.appendTail(out);return out.toString();}
 private void validateJson(String value){try{Object o=JSON.parseObject(value);if(!(o instanceof Map))throw new Exception();}catch(Exception e){throw new MSException("PROMPT_VARIABLE_SCHEMA_INVALID");}}private String normalize(String v){return JSON.toJSONString(JSON.parseObject(v));}
 private AgentPromptTemplateVersionDTO map(java.sql.ResultSet r,int n)throws java.sql.SQLException{AgentPromptTemplateVersionDTO d=new AgentPromptTemplateVersionDTO();d.setId(r.getString("id"));d.setPromptTemplateId(r.getString("prompt_template_id"));d.setOrganizationId(r.getString("organization_id"));d.setName(r.getString("name"));d.setVersionNo(r.getInt("version_no"));d.setSystemTemplate(r.getString("system_template"));d.setBusinessTemplate(r.getString("business_template"));d.setVariableSchema(r.getString("variable_schema"));d.setOutputSchemaVersion(r.getString("output_schema_version"));d.setContentHash(r.getString("content_hash"));d.setStatus(r.getString("status"));d.setPublishedBy(r.getString("published_by"));long at=r.getLong("published_at");d.setPublishedAt(r.wasNull()?null:at);d.setCreateUser(r.getString("create_user"));d.setCreateTime(r.getLong("create_time"));return d;}
}
